name: Release Multiplatform Binaries

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Trigger release job only on tags like v1.0.0, v2.1.0-beta

env:
  CARGO_TERM_COLOR: always # Keep Cargo output colored in CI logs

jobs:
  # Build Linux and Windows targets (cross-compiled on Ubuntu)
  build_linux_windows:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Allow other builds to continue if one fails
      matrix:
        # Define cross-compilation targets
        target:
          - x86_64-unknown-linux-gnu # Linux (x86_64)
          - aarch64-unknown-linux-gnu # Linux (ARM64)
          - x86_64-pc-windows-msvc # Windows (x86_64)
          - aarch64-pc-windows-msvc # Windows (ARM64)

        include:
          - target: x86_64-unknown-linux-gnu
            os_suffix: linux-x64
            archive_ext: tar.gz
            installer_deps: ""
          - target: aarch64-unknown-linux-gnu
            os_suffix: linux-arm64
            archive_ext: tar.gz
            installer_deps: "gcc-aarch64-linux-gnu"
          - target: x86_64-pc-windows-msvc
            os_suffix: windows-x64
            archive_ext: zip
            installer_deps: "clang llvm lld"
          - target: aarch64-pc-windows-msvc
            os_suffix: windows-arm64
            archive_ext: zip
            installer_deps: "clang llvm lld"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- Install protoc ---
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: '25.x' # Use the latest version from Protobuf 25 series

    - name: Install target-specific build dependencies
      if: ${{ matrix.installer_deps != '' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.installer_deps }}

    # For Windows MSVC ARM64 targets, prepare environment
    - name: Setup MSVC for Windows ARM64
      if: ${{ matrix.target == 'aarch64-pc-windows-msvc' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 clang llvm lld
        echo 'CARGO_TARGET_AARCH64_PC_WINDOWS_MSVC_LINKER=lld-link' >> $GITHUB_ENV
        echo 'CARGO_TARGET_AARCH64_PC_WINDOWS_MSVC_AR=llvm-ar' >> $GITHUB_ENV

    - name: Set up Rust toolchain for ${{ matrix.target }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.target }}-

    - name: Build release binaries for ${{ matrix.target }}
      run: cargo build --release --workspace --target ${{ matrix.target }}

    - name: Prepare and archive binaries for ${{ matrix.target }}
      shell: bash
      run: |
        BUILD_DIR="mq-${{ matrix.os_suffix }}"
        mkdir -p "$BUILD_DIR"

        TARGET_DIR="target/${{ matrix.target }}/release"
        declare -a BINARY_NAMES=("mq-server" "mq-client" "mq-monitoring")

        FOUND_BINARIES=""
        for BIN_NAME in "${BINARY_NAMES[@]}"; do
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            if [ -f "${TARGET_DIR}/${BIN_NAME}.exe" ]; then
              FOUND_BINARIES+="${TARGET_DIR}/${BIN_NAME}.exe "
            fi
          else
            if [ -f "${TARGET_DIR}/${BIN_NAME}" ]; then
              FOUND_BINARIES+="${TARGET_DIR}/${BIN_NAME} "
            fi
          fi
        done

        if [ -z "$FOUND_BINARIES" ]; then
          echo "Warning: No executable binaries found for target ${{ matrix.target }} in ${TARGET_DIR}."
          echo "Please ensure all expected binaries are built and match the names in BINARY_NAMES array."
          # exit 1 # Uncomment to fail if none found
        fi

        cp $FOUND_BINARIES "$BUILD_DIR/"

        ARCHIVE_NAME="${BUILD_DIR}.${{ matrix.archive_ext }}"
        if [[ "${{ matrix.archive_ext }}" == "zip" ]]; then
          tar -a -cvf "${ARCHIVE_NAME}" "$BUILD_DIR"
        else
          tar -czvf "${ARCHIVE_NAME}" "$BUILD_DIR"
        fi

        echo "ASSET_PATH=${ARCHIVE_NAME}" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ASSET_PATH }}
        path: ${{ env.ASSET_PATH }}

  # Build macOS targets (natively on macOS Runner)
  build_macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

        include:
          - target: x86_64-apple-darwin
            os_suffix: macos-x64
          - target: aarch64-apple-darwin
            os_suffix: macos-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: '25.x'

    - name: Set up Rust toolchain for ${{ matrix.target }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.target }}-

    - name: Build release binaries for ${{ matrix.target }}
      run: cargo build --release --workspace --target ${{ matrix.target }}

    - name: Prepare and archive binaries for ${{ matrix.target }}
      shell: bash
      run: |
        BUILD_DIR="mq-${{ matrix.os_suffix }}"
        mkdir -p "$BUILD_DIR"

        TARGET_DIR="target/${{ matrix.target }}/release"
        declare -a BINARY_NAMES=("mq-server" "mq-client" "mq-monitoring")

        FOUND_BINARIES=""
        for BIN_NAME in "${BINARY_NAMES[@]}"; do
          if [ -f "${TARGET_DIR}/${BIN_NAME}" ]; then
            FOUND_BINARIES+="${TARGET_DIR}/${BIN_NAME} "
          fi
        done

        if [ -z "$FOUND_BINARIES" ]; then
          echo "Warning: No executable binaries found for target ${{ matrix.target }} in ${TARGET_DIR}."
          exit 1
        fi

        cp $FOUND_BINARIES "$BUILD_DIR/"

        ARCHIVE_NAME="${BUILD_DIR}.tar.gz"
        tar -czvf "${ARCHIVE_NAME}" "$BUILD_DIR"

        echo "ASSET_PATH=${ARCHIVE_NAME}" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ASSET_PATH }}
        path: ${{ env.ASSET_PATH }}

  # Release Job
  release:
    needs: [build_linux_windows, build_macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: |
          # Release Notes for ${{ github.ref }}

          This release provides multi-platform binaries for the `mq` message queue system.

          ### Architectures supported:
          - Linux (x86_64, ARM64)
          - Windows (x86_64, ARM64)
          - macOS (x86_64, ARM64)

          ### Binaries included:
          - `mq-server`
          - `mq-client`
          - `mq-monitoring`

          ---
          *(Auto-generated by GitHub Actions)*
        draft: false
        prerelease: false
        files: ./artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}